import Head from "next/head";
import Login from "./components/login";
import { useEffect, useState } from "react";
import UserTable from "./components/userTable";
import axios from "axios";

export default function Home() {
  const [showLogin, setShowLogin] = useState(true);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [emailError, setEmailError] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const [showLoader, setShowLoader] = useState(true);
  const [userData, setUserData] = useState([]);
  useEffect(() => {
    let user = JSON.parse(localStorage.getItem("user"));
    if (user && user.email === "admin@mypgbooking.com") {
      setShowLogin(false);
      axios
        .get("/api/contact")
        .then((res) => {
          setUserData(res.data);
          setShowLoader(false);
        })
        .catch((err) => {
          setShowLoader(false);
          console.log(err);
        });
    } else {
      setShowLogin(true);
      setShowLoader(false);
    }
  }, []);

  const login = (e) => {
    e.preventDefault();
    if (email === "admin@mypgbooking.com" && password === "admin123") {
      localStorage.setItem(
        "user",
        JSON.stringify({ email: "admin@mypgbooking.com" })
      );
      setShowLogin(false);
    } else {
      if (email !== "admin@mypgbooking.com") {
        setEmailError("Invalid email");
      }
      if (password !== "admin123") {
        setPasswordError("Invalid password");
      }
    }
  };
  const logout = () => {
    localStorage.removeItem("user");
    setShowLogin(true);
  };

  const handleDelete = (data) => {
    axios
      .delete("/api/contact?mobile=" + data.mobile)
      .then((resp) => {
        if (resp.data.status === "success") {
          axios
            .get("/api/contact")
            .then((res) => {
              setUserData(res.data);
              setShowLoader(false);
            })
            .catch((err) => {
              setShowLoader(false);
              console.log(err);
            });
        }
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Admin</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {showLoader && <div class="loader"></div>}
      {showLogin ? (
        <Login
          email={email}
          password={password}
          setEmail={setEmail}
          setPassword={setPassword}
          emailError={emailError}
          passwordError={passwordError}
          login={login}
        />
      ) : (
        <UserTable
          userData={userData}
          logout={logout}
          handleDelete={handleDelete}
        />
      )}
    </>
  );
}
