import Head from "next/head";
import { useEffect } from "react";
import Banner from "./components/bannner";
import Contact from "./components/contact";
import Features from "./components/features";
import Footer from "./components/footer";
import Header from "./components/header";
import Product from "./components/product";
const isServer = typeof window === "undefined";
const WOW = !isServer ? require("wow.js") : null;

export default function Home() {
  useEffect(() => {
    new WOW().init();
  }, []);
  return (
    <>
      <Head>
        <title>Pg Homes</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Banner />
      <Features />
      <Product />
      <Contact />
      <Footer />
      <a href="https://wa.me/+919911083130?text=Hi" className="float_icon">
        <img src="/whatsapp.png" />
      </a>
    </>
  );
}
